"""empty message

Revision ID: 8edee7198c26
Revises: 61cdec295291
Create Date: 2026-08-06 22:05:35.250682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edee7198c26'
down_revision: Union[str, Sequence[str], None] = '61cdec295291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demos', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'demos', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demos', type_='unique')
    op.drop_column('demos', 'email')
    # ### end Alembic commands ###
