"""create session table

Revision ID: e1d8698c0dd3
Revises: 8edee7198c26
Create Date: 2026-08-25 20:32:38.813668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1d8698c0dd3'
down_revision: Union[str, Sequence[str], None] = '8edee7198c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('sandbox_id', sa.String(length=255), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('unread_message_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('latest_message', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('latest_message_at', sa.DateTime(), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('memories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(9)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(9)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_sessions_id')
    )
    op.drop_table('demos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demos_id')),
    sa.UniqueConstraint('email', name=op.f('demos_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('sessions')
    # ### end Alembic commands ###
